
# SEO settings
title: WTF-Dev
description: "Coding and Web Development for Poets"
keywords: "tutorials"
url: http://wtf-dev.com
baseurl: null

google_analytics: UA-87605039-1
repo: http://github.com/wtf-dev
disqus_shortname: "wtf-dev"

# Build settings
permalink   : /:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 4
paginate_path: "/page/:num/"
comments: true

source: source
destination: _site

# Sass configuration
sass:
  sass_dir: assets/scss
  style: compressed # expanded

# Author settings
author:
  name     : Ryan Borker
  job      : Product Guy
  bio      : "I write a lot. and occasionally code"
  thumb    : /images/author.jpg
  email    : borker@mit.edu
  url      : borker.co
  github   : http://github.com/wtf-dev
  twitter  : http://twitter.com/borker
#  facebook : http://facebook.com/fernando.dev
#  linkedin : http://linkedin.com/in/nandomoreirame
  quora    : www.quora.com/

# social settings
#og_locale: "pt_BR"
twitter_card: "summary_large_image"
twitter_site: "borker"

gems:
  - bourbon
  - jekyll-paginate

# navbar pages
navbar:
  - slug : about
    title: About
  - slug : blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
